### ISSUE TITLE
No documentation on how to install XC32 compiler for compiling contiki

### ISSUE THREAD

**Issue by seank-img** [CreatorKit/creator-docs#16]
I could not find any documentation on how to install the XC32 compiler, here is some internal documentation I found:

### Cross-Compiling Contiki

 Building the Contiki image for a Seedeye or MikroE Clicker board currently requires Linux.

#### Microchip Toolchain Installation

 Before targets can be compiled, the cross-compiler toolchain must be installed.

 For 64-bit Ubuntu, 32-bit runtime libraries must be installed before the XC32 compiler can be run:

    $ sudo apt-get install libc6:i386

 For 64bit Ubuntu the package lib32ncurses5 may also be required.

 Installing the microchip XC32 compiler (~100 MB):

    $ wget http://ww1.microchip.com/downloads/en/DeviceDoc/xc32-v1.34-full-install-linux-installer.run
    $ chmod a+x xc32-v1.34-full-install-linux-installer.run
    $ sudo ./xc32-v1.34-full-install-linux-installer.run --mode unattended --Add\ to\ PATH 1 --debuglevel 4 --installerfunction installcompiler --netservername localhost
    # no output expected
    $ . ~/.bashrc
    $ xc32-gcc --version
    xc32-gcc (Microchip Technology) 4.5.2 MPLAB XC32 Compiler v1.34 Build date: Nov 21 2014
    Part support version: 1.34 (A)
    ...

 There are reports that the installer does not modified PATH correctly. If trying to run xc32-gcc results in "command not found", modify your .bashrc to set the path correctly:

    $ echo "export PATH=\$PATH:/opt/microchip/xc32/v1.34/bin" >> ~/.bashrc
    $ . ~/.bashrc

**Comment by nikhil-zinjurde-imgtec** [comment]
@MattAtkinson can you please update this in the Toolbox.md?

**Comment by nikhil-zinjurde-imgtec** [comment]
It's done
